version: '3'
services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: driverstats
      POSTGRES_USER: driverstats
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    image: driverstats/api
    volumes:
      - driverstats:/home/driverstats/data
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=driverstats
      - DB_USER=driverstats
      - DB_PASSWORD=postgres
      - DB_SSLMODE=disable
      - API_URL=http://dev.driverstats.org
      - STORAGE_PATH=/home/driverstats/data
    ports:
      - "8080:8080"
  client:
    image: driverstats/client
    environment:
      - API_URL=http://dev.driverstats.org:8080
      - HTTPS_DISABLE=true
    ports:
      - "80:80"
volumes:
  database:
  driverstats:
